POST http://127.0.0.1:8000/
content-type: application/json

{
    "username": "Josh",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://127.0.0.1:8000/api/register/
content-type: application/json

{
    "username": "TaimoK",
    "password": "Thisisademo",
    "email": "Taimok@mail.utoronto.ca",
    "teacher": "False",
    "first_name": "Taimo",
    "last_name": "K",
    "title": null,
    "pos": "Anthropology",
    "gpa": "4.0",
    "grad_year": "2025",
    "minors": ["None"]
}

###
# @name login
POST http://127.0.0.1:8000/api/token/
content-type: application/json

{
    "username": "paul.dup",
    "password": "12345"
}

###
@jwtoken = {{login.response.body.$.access}}

###
POST http://127.0.0.1:8000/api/updateProfile/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{ 
    "email": "TaimoK@mail.utoronto.ca",
    "profile": {
        "courseCode": "ECE496",
        "hoursToCommit": "10",
        "interests": ["Horses", "Money", "Cars"],
        "skills": ["C++", "Python", "Programming"]
    }
}
###

###
POST http://127.0.0.1:8000/api/updateSelf/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "first_name": "Josh",
    "last_name": "LaPointe",
    "pos": "Software Engineering",
    "gpa": "4.0",
    "teacher": "True",
    "grad_year": "2025",
    "minors": ["AI"]
}

###
POST http://127.0.0.1:8000/api/getSelf/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "email": "josh.lapointe@mail.utoronto.ca"
}

###
POST http://127.0.0.1:8000/api/getUser/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "requested_user": "JohnDoe1234"
}

###
POST http://127.0.0.1:8000/api/createCourse/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "courseInfo": {
        "courseCode": "LOL200",
        "courseName": "Quitting League of Legends",
        "description": "Hear harrowing stories from surivivors of Summoner's Rift, and learn how to overcome your League of Legends addicition.",
        "session": "Summer",
        "year": 2026,
        "groupSize": "3"
    }
}

###
POST http://127.0.0.1:8000/api/scheduleMatch/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "courseInfo": {
        "courseCode": "ECE496",
        "matchDate": "2025-02-12T14:53:58.-0500"
    }
}
###
POST http://127.0.0.1:8000/api/listUserCourses/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
}
###
POST http://127.0.0.1:8000/api/listUsersInCourse/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "courseCode": "ECE496"
}
###
POST http://127.0.0.1:8000/api/listCourses/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
}

###
POST http://127.0.0.1:8000/api/addReview/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "reviewee": "guest",
    "score": 3,
    "comment": "Terrible teammate."
}

###
DELETE http://127.0.0.1:8000/api/deleteReview/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "review_id": 4
}

###
GET http://127.0.0.1:8000/api/getReviews/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
}