POST http://127.0.0.1:8000/
content-type: application/json

{
    "username": "Josh",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://127.0.0.1:8000/api/register/
content-type: application/json

{
    "username": "JoshLa.",
    "password": "Thisisademo",
    "email": "josh.lapointe@mail.utoronto.ca",
    "teacher": "True",
    "first_name": "Josh",
    "last_name": "Lapointe",
    "pos": "Computer Engineering",
    "gpa": "4.0",
    "grad_year": "2025",
    "minors": ["None"]
}

###
# @name login
POST http://127.0.0.1:8000/api/token/
content-type: application/json

{
    "username": "teacher",
    "password": "Thisisatest"
}

###
@jwtoken = {{login.response.body.$.access}}

###
POST http://127.0.0.1:8000/api/updateProfile/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{ 
    "email": "josh.lapointe@mail.utoronto.ca",
    "profile": {
        "courseCode": "ECE496",
        "hoursToCommit": "9",
        "interests": ["French", "Computers", "Cars"],
        "skills": ["C++", "Python", "Programming"]
    }
}
###

###
POST http://127.0.0.1:8000/api/updateSelf/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "first_name": "Josh",
    "last_name": "LaPointe",
    "pos": "Software Engineering",
    "gpa": "4.0",
    "teacher": "True",
    "grad_year": "2025",
    "minors": ["AI"]
}

###
POST http://127.0.0.1:8000/api/getSelf/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "email": "josh.lapointe@mail.utoronto.ca"
}

###
POST http://127.0.0.1:8000/api/getUser/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "requested_user": "JohnDoe1234"
}

###
POST http://127.0.0.1:8000/api/matchTeams/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "courseCode": "CIV220"
}

###
POST http://127.0.0.1:8000/api/createCourse/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "courseInfo": {
        "courseCode": "MIE200",
        "courseName": "Dynamics"
    }
}

###
POST http://127.0.0.1:8000/api/scheduleMatch/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
    "courseInfo": {
        "courseCode": "CIV220",
        "matchDate": "2025-02-05T18:35:58.-0500"
    }
}
###
POST http://127.0.0.1:8000/api/listCourses/
Content-Type: application/json
Authorization: Bearer {{jwtoken}}

{
}