services:
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install --include=dev && npm run build
    startCommand: cd frontend && npm install --include=dev && npm run preview -- --host
    envVars:
      - key: NODE_ENV
        value: production
    
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python manage.py migrate && gunicorn TeamBuilder.wsgi:application --bind=0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: TeamBuilder.settings_prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
    disk:
      name: sqlite-data
      mountPath: backend
      sizeGB: 1 