FROM python:3.12

WORKDIR /app/backend
 
# Set environment variables 
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
RUN pip install --upgrade pip 
 
COPY ./backend/requirements.txt  /app/backend/
 
RUN cd /app/backend && pip install -r requirements.txt
 
COPY ./backend /app/backend
 
EXPOSE 8000
