FROM python:3.12

WORKDIR /app
 
# Set environment variables 
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
RUN pip install --upgrade pip --no-warn-script-location
 
COPY ./backend/requirements.txt  /app/backend/
 
RUN cd /app/backend && pip install -r requirements.txt --no-warn-script-location --root-user-action=ignore
 
COPY ./backend /app/backend

# Ensure manage.py is executable
RUN chmod +x /app/backend/manage.py
 
EXPOSE 8000

# Run Django commands and start gunicorn
CMD cd /app/backend && \
    python manage.py collectstatic --noinput && \
    python manage.py migrate && \
    gunicorn --bind 0.0.0.0:$PORT TeamBuilder.wsgi
